import imgMA from "../assets/images/GIRLS/MAKEUP/1.jpg"
import imgMB from "../assets/images/GIRLS/MAKEUP/2.jpg"
import imgMC from "../assets/images/GIRLS/MAKEUP/3.jpg"
import imgMD from "../assets/images/GIRLS/MAKEUP/4.jpg"
import imgMI from "../assets/images/GIRLS/MAKEUP/5.jpg"
import imgMF from "../assets/images/GIRLS/MAKEUP/6.jpg"
import imgMG from "../assets/images/GIRLS/MAKEUP/7.jpg"

import imgSG1 from "../assets/images/GIRLS/STUDIO/1.jpg"
import imgSG2 from "../assets/images/GIRLS/STUDIO/2.jpg"
import imgSG3 from "../assets/images/GIRLS/STUDIO/3.jpg"
import imgSG4 from "../assets/images/GIRLS/STUDIO/4.jpg"
import imgSG5 from "../assets/images/GIRLS/STUDIO/5.jpg"
import imgSG6 from "../assets/images/GIRLS/STUDIO/6.jpg"
import imgSG7 from "../assets/images/GIRLS/STUDIO/7.jpg"
import imgSG8 from "../assets/images/GIRLS/STUDIO/8.jpg"
import imgSG9 from "../assets/images/GIRLS/STUDIO/9.jpg"
import imgSG10 from "../assets/images/GIRLS/STUDIO/10.jpg"
import imgSG11 from "../assets/images/GIRLS/STUDIO/11.jpg"
import imgSG12 from "../assets/images/GIRLS/STUDIO/12.jpg"
import imgSG13 from "../assets/images/GIRLS/STUDIO/13.jpg"
import imgSG14 from "../assets/images/GIRLS/STUDIO/14.jpg"
import imgSG15 from "../assets/images/GIRLS/STUDIO/15.jpg"
import imgSG16 from "../assets/images/GIRLS/STUDIO/16.jpg"
import imgSG17 from "../assets/images/GIRLS/STUDIO/17.jpg"
import imgSG18 from "../assets/images/GIRLS/STUDIO/18.jpg"
import imgSG19 from "../assets/images/GIRLS/STUDIO/19.jpg"
import imgSG20 from "../assets/images/GIRLS/STUDIO/20.jpg"
import imgSG21 from "../assets/images/GIRLS/STUDIO/21.jpg"
import imgSG22 from "../assets/images/GIRLS/STUDIO/22.jpg"
import imgSG23 from "../assets/images/GIRLS/STUDIO/23.jpg"
import imgSG24 from "../assets/images/GIRLS/STUDIO/24.jpg"
import imgSG25 from "../assets/images/GIRLS/STUDIO/25.jpg"
import imgSG26 from "../assets/images/GIRLS/STUDIO/26.jpg"
import imgSG27 from "../assets/images/GIRLS/STUDIO/27.jpg"
import imgSG28 from "../assets/images/GIRLS/STUDIO/28.jpg"
import imgSG29 from "../assets/images/GIRLS/STUDIO/29.jpg"
import imgSG30 from "../assets/images/GIRLS/STUDIO/30.jpg"
import imgSG31 from "../assets/images/GIRLS/STUDIO/31.jpg"
import imgSG32 from "../assets/images/GIRLS/STUDIO/32.jpg"
import imgSG33 from "../assets/images/GIRLS/STUDIO/33.jpg"
import imgSG34 from "../assets/images/GIRLS/STUDIO/34.jpg"
import imgSG35 from "../assets/images/GIRLS/STUDIO/35.jpg"
import imgSG36 from "../assets/images/GIRLS/STUDIO/36.jpg"
import imgSG37 from "../assets/images/GIRLS/STUDIO/37.jpg"
import imgSG38 from "../assets/images/GIRLS/STUDIO/38.jpg"
import imgSG39 from "../assets/images/GIRLS/STUDIO/39.jpg"
import imgSG40 from "../assets/images/GIRLS/STUDIO/40.jpg"
import imgSG41 from "../assets/images/GIRLS/STUDIO/41.jpg"
import imgSG42 from "../assets/images/GIRLS/STUDIO/42.jpg"
import imgSG43 from "../assets/images/GIRLS/STUDIO/43.jpg"
import imgSG44 from "../assets/images/GIRLS/STUDIO/44.jpg"
import imgSG45 from "../assets/images/GIRLS/STUDIO/45.jpg"
import imgSG46 from "../assets/images/GIRLS/STUDIO/46.jpg"
import imgSG47 from "../assets/images/GIRLS/STUDIO/47.jpg"
import imgSG48 from "../assets/images/GIRLS/STUDIO/48.jpg"
import imgSG49 from "../assets/images/GIRLS/STUDIO/49.jpg"
import imgSG50 from "../assets/images/GIRLS/STUDIO/50.jpg"
import imgSG51 from "../assets/images/GIRLS/STUDIO/51.jpg"
import imgSG52 from "../assets/images/GIRLS/STUDIO/52.jpg"
import imgSG53 from "../assets/images/GIRLS/STUDIO/53.jpg"
import imgSG54 from "../assets/images/GIRLS/STUDIO/54.jpg"
import imgSG55 from "../assets/images/GIRLS/STUDIO/55.jpg"
import imgSG56 from "../assets/images/GIRLS/STUDIO/56.jpg"
import imgSG57 from "../assets/images/GIRLS/STUDIO/57.jpg"
import imgSG61 from "../assets/images/GIRLS/STUDIO/61.jpg"
import imgSG62 from "../assets/images/GIRLS/STUDIO/62.jpg"
import imgSG63 from "../assets/images/GIRLS/STUDIO/63.jpg"
import imgSG64 from "../assets/images/GIRLS/STUDIO/64.jpg"

import imgWG1 from "../assets/images/GIRLS/WALKING/1.jpg"
import imgWG2 from "../assets/images/GIRLS/WALKING/2.jpg"
import imgWG3 from "../assets/images/GIRLS/WALKING/3.jpg"
import imgWG4 from "../assets/images/GIRLS/WALKING/4.jpg"
import imgWG5 from "../assets/images/GIRLS/WALKING/5.jpg"
import imgWG6 from "../assets/images/GIRLS/WALKING/6.jpg"


const imgGirls=[imgMA, imgMB,imgMC,imgMD, imgMI, imgMF, imgMG, imgSG1, imgSG2, imgSG3, imgSG4, imgSG5, imgSG6, imgSG7, imgSG8,  imgSG9, imgSG10, imgSG11,
 imgSG12, imgSG13, imgSG14, imgSG15, imgSG16, imgSG17, imgSG18, imgSG19, imgSG20, imgSG21, imgSG22, imgSG23, imgSG24, imgSG25, imgSG26, imgSG27, imgSG28, imgSG29, imgSG30,
 imgSG31, imgSG32, imgSG33, imgSG34, imgSG35, imgSG36, imgSG37, imgSG38, imgSG39, imgSG40, imgSG41, imgSG42, imgSG43, imgSG44, imgSG45, imgSG46,
 imgSG47, imgSG48, imgSG49, imgSG50, imgSG51, imgSG52, imgSG53, imgSG54, imgSG55, imgSG56, imgSG57, imgSG61, imgSG62, imgSG63, imgSG64,
 imgWG1, imgWG2, imgWG3, imgWG4, imgWG5, imgWG6]

export default imgGirls
